//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_dungeon_tile_H
#define METASPRITE_dungeon_tile_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define dungeon_tile_TILE_ORIGIN 0
#define dungeon_tile_TILE_W 8
#define dungeon_tile_TILE_H 8
#define dungeon_tile_WIDTH 64
#define dungeon_tile_HEIGHT 32
#define dungeon_tile_TILE_COUNT 29
#define dungeon_tile_PALETTE_COUNT 1
#define dungeon_tile_COLORS_PER_PALETTE 4
#define dungeon_tile_TOTAL_COLORS 4

BANKREF_EXTERN(dungeon_tile)

extern const palette_color_t dungeon_tile_palettes[4];
extern const uint8_t dungeon_tile_tiles[464];

#endif
