//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_dungeon_map_H
#define METASPRITE_dungeon_map_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define dungeon_map_TILE_ORIGIN 0
#define dungeon_map_TILE_W 8
#define dungeon_map_TILE_H 8
#define dungeon_map_WIDTH 160
#define dungeon_map_HEIGHT 144
#define dungeon_map_TILE_COUNT 0
#define dungeon_map_PALETTE_COUNT 1
#define dungeon_map_COLORS_PER_PALETTE 4
#define dungeon_map_TOTAL_COLORS 4
#define dungeon_map_MAP_ATTRIBUTES 0
extern const unsigned char dungeon_map_map[360];
#define dungeon_map_map_attributes dungeon_map_map

BANKREF_EXTERN(dungeon_map)


#endif
