//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_dungeon_tileset_H
#define METASPRITE_dungeon_tileset_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define dungeon_tileset_TILE_ORIGIN 0
#define dungeon_tileset_TILE_W 8
#define dungeon_tileset_TILE_H 8
#define dungeon_tileset_WIDTH 16
#define dungeon_tileset_HEIGHT 128
#define dungeon_tileset_TILE_COUNT 29
#define dungeon_tileset_PALETTE_COUNT 1
#define dungeon_tileset_COLORS_PER_PALETTE 4
#define dungeon_tileset_TOTAL_COLORS 4

BANKREF_EXTERN(dungeon_tileset)

extern const palette_color_t dungeon_tileset_palettes[4];
extern const uint8_t dungeon_tileset_tiles[464];

#endif
