//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_playersprites_H
#define METASPRITE_playersprites_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define playersprites_TILE_ORIGIN 0
#define playersprites_TILE_W 8
#define playersprites_TILE_H 8
#define playersprites_WIDTH 16
#define playersprites_HEIGHT 32
#define playersprites_TILE_COUNT 38
#define playersprites_PALETTE_COUNT 1
#define playersprites_COLORS_PER_PALETTE 4
#define playersprites_TOTAL_COLORS 4
#define playersprites_PIVOT_X 8
#define playersprites_PIVOT_Y 16
#define playersprites_PIVOT_W 16
#define playersprites_PIVOT_H 32
extern const metasprite_t* const playersprites_metasprites[8];

BANKREF_EXTERN(playersprites)

extern const palette_color_t playersprites_palettes[4];
extern const uint8_t playersprites_tiles[608];

#endif
