//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_gb_numbers_H
#define METASPRITE_gb_numbers_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define gb_numbers_TILE_ORIGIN 0
#define gb_numbers_TILE_W 8
#define gb_numbers_TILE_H 8
#define gb_numbers_WIDTH 8
#define gb_numbers_HEIGHT 8
#define gb_numbers_TILE_COUNT 10
#define gb_numbers_PALETTE_COUNT 1
#define gb_numbers_COLORS_PER_PALETTE 4
#define gb_numbers_TOTAL_COLORS 4
#define gb_numbers_PIVOT_X 4
#define gb_numbers_PIVOT_Y 4
#define gb_numbers_PIVOT_W 8
#define gb_numbers_PIVOT_H 8
extern const metasprite_t* const gb_numbers_metasprites[10];

BANKREF_EXTERN(gb_numbers)

extern const palette_color_t gb_numbers_palettes[4];
extern const uint8_t gb_numbers_tiles[160];

#endif
