//AUTOGENERATED FILE FROM png2asset
// Conversion args: /boss_beholder_sprite.png -c boss_beholder_sprite.c -sw 32 -sh 32 -spr8x16 -noflip -keep_palette_order

#ifndef METASPRITE_boss_beholder_sprite_H
#define METASPRITE_boss_beholder_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define boss_beholder_sprite_TILE_ORIGIN 0
#define boss_beholder_sprite_TILE_W 8
#define boss_beholder_sprite_TILE_H 16
#define boss_beholder_sprite_WIDTH 32
#define boss_beholder_sprite_HEIGHT 32
#define boss_beholder_sprite_TILE_COUNT 24
#define boss_beholder_sprite_PALETTE_COUNT 1
#define boss_beholder_sprite_COLORS_PER_PALETTE 4
#define boss_beholder_sprite_TOTAL_COLORS 4
#define boss_beholder_sprite_PIVOT_X 16
#define boss_beholder_sprite_PIVOT_Y 16
#define boss_beholder_sprite_PIVOT_W 32
#define boss_beholder_sprite_PIVOT_H 32
extern const metasprite_t* const boss_beholder_sprite_metasprites[2];

BANKREF_EXTERN(boss_beholder_sprite)

extern const palette_color_t boss_beholder_sprite_palettes[4];
extern const uint8_t boss_beholder_sprite_tiles[384];

#endif
