//AUTOGENERATED FILE FROM png2asset
// Conversion args: /enemy_minion_sprite.png -c enemy_minion_sprite.c -sw 16 -sh 16 -spr8x16 -noflip -keep_palette_order

#ifndef METASPRITE_enemy_minion_sprite_H
#define METASPRITE_enemy_minion_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define enemy_minion_sprite_TILE_ORIGIN 0
#define enemy_minion_sprite_TILE_W 8
#define enemy_minion_sprite_TILE_H 16
#define enemy_minion_sprite_WIDTH 16
#define enemy_minion_sprite_HEIGHT 16
#define enemy_minion_sprite_TILE_COUNT 8
#define enemy_minion_sprite_PALETTE_COUNT 1
#define enemy_minion_sprite_COLORS_PER_PALETTE 4
#define enemy_minion_sprite_TOTAL_COLORS 4
#define enemy_minion_sprite_PIVOT_X 8
#define enemy_minion_sprite_PIVOT_Y 8
#define enemy_minion_sprite_PIVOT_W 16
#define enemy_minion_sprite_PIVOT_H 16
extern const metasprite_t* const enemy_minion_sprite_metasprites[2];

BANKREF_EXTERN(enemy_minion_sprite)

extern const palette_color_t enemy_minion_sprite_palettes[4];
extern const uint8_t enemy_minion_sprite_tiles[128];

#endif
