//AUTOGENERATED FILE FROM png2asset
// Conversion args: /explosion_sprite.png -c explosion_sprite.c -sw 16 -sh 16 -spr8x16 -noflip -keep_palette_order

#ifndef METASPRITE_explosion_sprite_H
#define METASPRITE_explosion_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define explosion_sprite_TILE_ORIGIN 0
#define explosion_sprite_TILE_W 8
#define explosion_sprite_TILE_H 16
#define explosion_sprite_WIDTH 16
#define explosion_sprite_HEIGHT 16
#define explosion_sprite_TILE_COUNT 16
#define explosion_sprite_PALETTE_COUNT 1
#define explosion_sprite_COLORS_PER_PALETTE 4
#define explosion_sprite_TOTAL_COLORS 4
#define explosion_sprite_PIVOT_X 8
#define explosion_sprite_PIVOT_Y 8
#define explosion_sprite_PIVOT_W 16
#define explosion_sprite_PIVOT_H 16
extern const metasprite_t* const explosion_sprite_metasprites[4];

BANKREF_EXTERN(explosion_sprite)

extern const palette_color_t explosion_sprite_palettes[4];
extern const uint8_t explosion_sprite_tiles[256];

#endif
