//AUTOGENERATED FILE FROM png2asset
// Conversion args: /gb_font.png -c gb_font.c -noflip -map -tiles_only -keep_palette_order

#ifndef METASPRITE_gb_font_H
#define METASPRITE_gb_font_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define gb_font_TILE_ORIGIN 0
#define gb_font_TILE_W 8
#define gb_font_TILE_H 8
#define gb_font_WIDTH 64
#define gb_font_HEIGHT 48
#define gb_font_TILE_COUNT 47
#define gb_font_PALETTE_COUNT 1
#define gb_font_COLORS_PER_PALETTE 4
#define gb_font_TOTAL_COLORS 4

BANKREF_EXTERN(gb_font)

extern const palette_color_t gb_font_palettes[4];
extern const uint8_t gb_font_tiles[752];

#endif
