//AUTOGENERATED FILE FROM png2asset
// Conversion args: /logo_img.png -c logo_img.c -map -noflip

#ifndef METASPRITE_logo_img_H
#define METASPRITE_logo_img_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define logo_img_TILE_ORIGIN 0
#define logo_img_TILE_W 8
#define logo_img_TILE_H 8
#define logo_img_WIDTH 160
#define logo_img_HEIGHT 32
#define logo_img_TILE_COUNT 67
#define logo_img_PALETTE_COUNT 1
#define logo_img_COLORS_PER_PALETTE 4
#define logo_img_TOTAL_COLORS 4
#define logo_img_MAP_ATTRIBUTES 0
extern const unsigned char logo_img_map[80];
#define logo_img_map_attributes logo_img_map

BANKREF_EXTERN(logo_img)

extern const palette_color_t logo_img_palettes[4];
extern const uint8_t logo_img_tiles[1072];

#endif
