//AUTOGENERATED FILE FROM png2asset
// Conversion args: /mini_player.png -c mini_player.c -noflip -map -tiles_only

#ifndef METASPRITE_mini_player_H
#define METASPRITE_mini_player_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define mini_player_TILE_ORIGIN 0
#define mini_player_TILE_W 8
#define mini_player_TILE_H 8
#define mini_player_WIDTH 8
#define mini_player_HEIGHT 8
#define mini_player_TILE_COUNT 1
#define mini_player_PALETTE_COUNT 1
#define mini_player_COLORS_PER_PALETTE 4
#define mini_player_TOTAL_COLORS 4

BANKREF_EXTERN(mini_player)

extern const palette_color_t mini_player_palettes[4];
extern const uint8_t mini_player_tiles[16];

#endif
