//AUTOGENERATED FILE FROM png2asset
// Conversion args: /mini_player.png -c mini_player.c -noflip -map -tiles_only

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(mini_player)

const palette_color_t mini_player_palettes[4] = {
	RGB8(255,255,255), RGB8(170,170,170), RGB8( 85, 85, 85), RGB8(  0,  0,  0)
	};

const uint8_t mini_player_tiles[16] = {
	0x00,0x00,0x00,0x10,0x38,0x00,0xb8,0x02,0xc8,0x16,0x44,0x00,0x38,0x00,0x00,0x00
	};

