//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_player_sprite_H
#define METASPRITE_player_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define player_sprite_TILE_ORIGIN 0
#define player_sprite_TILE_W 8
#define player_sprite_TILE_H 16
#define player_sprite_WIDTH 16
#define player_sprite_HEIGHT 16
#define player_sprite_TILE_COUNT 12
#define player_sprite_PALETTE_COUNT 1
#define player_sprite_COLORS_PER_PALETTE 4
#define player_sprite_TOTAL_COLORS 4
#define player_sprite_PIVOT_X 8
#define player_sprite_PIVOT_Y 8
#define player_sprite_PIVOT_W 16
#define player_sprite_PIVOT_H 16
extern const metasprite_t* const player_sprite_metasprites[3];

BANKREF_EXTERN(player_sprite)

extern const palette_color_t player_sprite_palettes[4];
extern const uint8_t player_sprite_tiles[192];

#endif
