//AUTOGENERATED FILE FROM png2asset
// Conversion args: /shield_sprite.png -c shield_sprite.c -sw 16 -sh 16 -spr8x16 -noflip -keep_palette_order

#ifndef METASPRITE_shield_sprite_H
#define METASPRITE_shield_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define shield_sprite_TILE_ORIGIN 0
#define shield_sprite_TILE_W 8
#define shield_sprite_TILE_H 16
#define shield_sprite_WIDTH 16
#define shield_sprite_HEIGHT 16
#define shield_sprite_TILE_COUNT 4
#define shield_sprite_PALETTE_COUNT 1
#define shield_sprite_COLORS_PER_PALETTE 4
#define shield_sprite_TOTAL_COLORS 4
#define shield_sprite_PIVOT_X 8
#define shield_sprite_PIVOT_Y 8
#define shield_sprite_PIVOT_W 16
#define shield_sprite_PIVOT_H 16
extern const metasprite_t* const shield_sprite_metasprites[1];

BANKREF_EXTERN(shield_sprite)

extern const palette_color_t shield_sprite_palettes[4];
extern const uint8_t shield_sprite_tiles[64];

#endif
