//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_shot_sprite_H
#define METASPRITE_shot_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define shot_sprite_TILE_ORIGIN 0
#define shot_sprite_TILE_W 8
#define shot_sprite_TILE_H 16
#define shot_sprite_WIDTH 8
#define shot_sprite_HEIGHT 16
#define shot_sprite_TILE_COUNT 6
#define shot_sprite_PALETTE_COUNT 1
#define shot_sprite_COLORS_PER_PALETTE 4
#define shot_sprite_TOTAL_COLORS 4

BANKREF_EXTERN(shot_sprite)

extern const palette_color_t shot_sprite_palettes[4];
extern const uint8_t shot_sprite_tiles[96];

#endif
