//AUTOGENERATED FILE FROM png2asset
// Conversion args: /space_bkg_tilemap.png -c space_bkg_tilemap.c -noflip -map -maps_only -source_tileset /space_bkg_tileset.png

#ifndef METASPRITE_space_bkg_tilemap_H
#define METASPRITE_space_bkg_tilemap_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define space_bkg_tilemap_TILE_ORIGIN 0
#define space_bkg_tilemap_TILE_W 8
#define space_bkg_tilemap_TILE_H 8
#define space_bkg_tilemap_WIDTH 160
#define space_bkg_tilemap_HEIGHT 256
#define space_bkg_tilemap_TILE_COUNT 0
#define space_bkg_tilemap_PALETTE_COUNT 1
#define space_bkg_tilemap_COLORS_PER_PALETTE 4
#define space_bkg_tilemap_TOTAL_COLORS 4
#define space_bkg_tilemap_MAP_ATTRIBUTES 0
extern const unsigned char space_bkg_tilemap_map[640];
#define space_bkg_tilemap_map_attributes space_bkg_tilemap_map

BANKREF_EXTERN(space_bkg_tilemap)


#endif
