//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_space_bkg_tileset_H
#define METASPRITE_space_bkg_tileset_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define space_bkg_tileset_TILE_ORIGIN 0
#define space_bkg_tileset_TILE_W 8
#define space_bkg_tileset_TILE_H 8
#define space_bkg_tileset_WIDTH 8
#define space_bkg_tileset_HEIGHT 80
#define space_bkg_tileset_TILE_COUNT 10
#define space_bkg_tileset_PALETTE_COUNT 1
#define space_bkg_tileset_COLORS_PER_PALETTE 4
#define space_bkg_tileset_TOTAL_COLORS 4

BANKREF_EXTERN(space_bkg_tileset)

extern const palette_color_t space_bkg_tileset_palettes[4];
extern const uint8_t space_bkg_tileset_tiles[160];

#endif
