/*

 WINMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 4
   Tile set      : Z:\home\meloni\Dev\gameboy\homebrew\5_window_display\res\wintiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __winmap_h_INCLUDE
#define __winmap_h_INCLUDE

#define winmapWidth 20
#define winmapHeight 4
#define winmapBank 0

extern const unsigned char winmap[];

#endif

/* End of WINMAP.H */
