//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bullet_sprite_H
#define METASPRITE_bullet_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bullet_sprite_TILE_ORIGIN 0
#define bullet_sprite_TILE_W 8
#define bullet_sprite_TILE_H 16
#define bullet_sprite_WIDTH 8
#define bullet_sprite_HEIGHT 16
#define bullet_sprite_TILE_COUNT 4
#define bullet_sprite_PALETTE_COUNT 1
#define bullet_sprite_COLORS_PER_PALETTE 4
#define bullet_sprite_TOTAL_COLORS 4

BANKREF_EXTERN(bullet_sprite)

extern const palette_color_t bullet_sprite_palettes[4];
extern const uint8_t bullet_sprite_tiles[64];

#endif
