//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_melstudio_H
#define METASPRITE_melstudio_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define melstudio_TILE_ORIGIN 0
#define melstudio_TILE_W 8
#define melstudio_TILE_H 8
#define melstudio_WIDTH 160
#define melstudio_HEIGHT 32
#define melstudio_TILE_COUNT 67
#define melstudio_PALETTE_COUNT 1
#define melstudio_COLORS_PER_PALETTE 4
#define melstudio_TOTAL_COLORS 4
#define melstudio_MAP_ATTRIBUTES 0
extern const unsigned char melstudio_map[80];
#define melstudio_map_attributes melstudio_map

BANKREF_EXTERN(melstudio)

extern const palette_color_t melstudio_palettes[4];
extern const uint8_t melstudio_tiles[1072];

#endif
