//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_spaceboost_title_H
#define METASPRITE_spaceboost_title_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define spaceboost_title_TILE_ORIGIN 0
#define spaceboost_title_TILE_W 8
#define spaceboost_title_TILE_H 8
#define spaceboost_title_WIDTH 160
#define spaceboost_title_HEIGHT 144
#define spaceboost_title_TILE_COUNT 166
#define spaceboost_title_PALETTE_COUNT 1
#define spaceboost_title_COLORS_PER_PALETTE 4
#define spaceboost_title_TOTAL_COLORS 4
#define spaceboost_title_MAP_ATTRIBUTES 0
extern const unsigned char spaceboost_title_map[360];
#define spaceboost_title_map_attributes spaceboost_title_map

BANKREF_EXTERN(spaceboost_title)

extern const palette_color_t spaceboost_title_palettes[4];
extern const uint8_t spaceboost_title_tiles[2656];

#endif
