//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_titlescreen_img_H
#define METASPRITE_titlescreen_img_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define titlescreen_img_TILE_ORIGIN 0
#define titlescreen_img_TILE_W 8
#define titlescreen_img_TILE_H 8
#define titlescreen_img_WIDTH 160
#define titlescreen_img_HEIGHT 144
#define titlescreen_img_TILE_COUNT 195
#define titlescreen_img_PALETTE_COUNT 1
#define titlescreen_img_COLORS_PER_PALETTE 4
#define titlescreen_img_TOTAL_COLORS 4
#define titlescreen_img_MAP_ATTRIBUTES 0
extern const unsigned char titlescreen_img_map[360];
#define titlescreen_img_map_attributes titlescreen_img_map

BANKREF_EXTERN(titlescreen_img)

extern const palette_color_t titlescreen_img_palettes[4];
extern const uint8_t titlescreen_img_tiles[3120];

#endif
