//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_carti_H
#define METASPRITE_carti_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define carti_TILE_ORIGIN 0
#define carti_TILE_W 8
#define carti_TILE_H 8
#define carti_WIDTH 16
#define carti_HEIGHT 16
#define carti_TILE_COUNT 14
#define carti_PALETTE_COUNT 1
#define carti_COLORS_PER_PALETTE 4
#define carti_TOTAL_COLORS 4
#define carti_PIVOT_X 8
#define carti_PIVOT_Y 8
#define carti_PIVOT_W 16
#define carti_PIVOT_H 16
extern const metasprite_t* const carti_metasprites[4];

BANKREF_EXTERN(carti)

extern const palette_color_t carti_palettes[4];
extern const uint8_t carti_tiles[224];

#endif
