//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_box_H
#define METASPRITE_box_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define box_TILE_ORIGIN 0
#define box_TILE_W 8
#define box_TILE_H 16
#define box_WIDTH 16
#define box_HEIGHT 16
#define box_TILE_COUNT 4
#define box_PALETTE_COUNT 1
#define box_COLORS_PER_PALETTE 4
#define box_TOTAL_COLORS 4
#define box_PIVOT_X 8
#define box_PIVOT_Y 8
#define box_PIVOT_W 16
#define box_PIVOT_H 16
extern const metasprite_t* const box_metasprites[1];

BANKREF_EXTERN(box)

extern const palette_color_t box_palettes[4];
extern const uint8_t box_tiles[64];

#endif
