//AUTOGENERATED FILE FROM png2asset
// Conversion args: /enemybullet_sprite.png -c enemybullet_sprite.c -sw 8 -sh 16 -spr8x16 -noflip -keep_palette_order -tiles_only

#ifndef METASPRITE_enemybullet_sprite_H
#define METASPRITE_enemybullet_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define enemybullet_sprite_TILE_ORIGIN 0
#define enemybullet_sprite_TILE_W 8
#define enemybullet_sprite_TILE_H 16
#define enemybullet_sprite_WIDTH 8
#define enemybullet_sprite_HEIGHT 16
#define enemybullet_sprite_TILE_COUNT 2
#define enemybullet_sprite_PALETTE_COUNT 1
#define enemybullet_sprite_COLORS_PER_PALETTE 4
#define enemybullet_sprite_TOTAL_COLORS 4

BANKREF_EXTERN(enemybullet_sprite)

extern const palette_color_t enemybullet_sprite_palettes[4];
extern const uint8_t enemybullet_sprite_tiles[32];

#endif
