//AUTOGENERATED FILE FROM png2asset
// Conversion args: /spaceship_sprite.png -c spaceship_sprite.c -sw 16 -sh 16 -spr8x16 -noflip -keep_palette_order

#ifndef METASPRITE_spaceship_sprite_H
#define METASPRITE_spaceship_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define spaceship_sprite_TILE_ORIGIN 0
#define spaceship_sprite_TILE_W 8
#define spaceship_sprite_TILE_H 16
#define spaceship_sprite_WIDTH 16
#define spaceship_sprite_HEIGHT 16
#define spaceship_sprite_TILE_COUNT 4
#define spaceship_sprite_PALETTE_COUNT 1
#define spaceship_sprite_COLORS_PER_PALETTE 4
#define spaceship_sprite_TOTAL_COLORS 4
#define spaceship_sprite_PIVOT_X 8
#define spaceship_sprite_PIVOT_Y 8
#define spaceship_sprite_PIVOT_W 16
#define spaceship_sprite_PIVOT_H 16
extern const metasprite_t* const spaceship_sprite_metasprites[1];

BANKREF_EXTERN(spaceship_sprite)

extern const palette_color_t spaceship_sprite_palettes[4];
extern const uint8_t spaceship_sprite_tiles[64];

#endif
