//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_booster_sprite_H
#define METASPRITE_booster_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define booster_sprite_TILE_ORIGIN 0
#define booster_sprite_TILE_W 8
#define booster_sprite_TILE_H 16
#define booster_sprite_WIDTH 8
#define booster_sprite_HEIGHT 16
#define booster_sprite_TILE_COUNT 8
#define booster_sprite_PALETTE_COUNT 1
#define booster_sprite_COLORS_PER_PALETTE 4
#define booster_sprite_TOTAL_COLORS 4
#define booster_sprite_PIVOT_X 4
#define booster_sprite_PIVOT_Y 8
#define booster_sprite_PIVOT_W 8
#define booster_sprite_PIVOT_H 16
extern const metasprite_t* const booster_sprite_metasprites[4];

BANKREF_EXTERN(booster_sprite)

extern const palette_color_t booster_sprite_palettes[4];
extern const uint8_t booster_sprite_tiles[128];

#endif
