//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(bullet_sprite)

const palette_color_t bullet_sprite_palettes[4] = {
	RGB8(255,255,255), RGB8(169,169,169), RGB8( 84, 84, 84), RGB8(  0,  0,  0)
	
};

const uint8_t bullet_sprite_tiles[32] = {
	0x00,0x00,0x00,0x18,
	0x18,0x24,0x18,0x24,
	0x3c,0x24,0x18,0x18,
	0x00,0x18,0x00,0x00,
	0x00,0x00,0x80,0x40,
	0x38,0x10,0x2c,0x31,
	0xc4,0xe6,0xcc,0xe6,
	0xc4,0xe6,0xcc,0xe6
	
};

const metasprite_t bullet_sprite_metasprite0[] = {
	METASPR_ITEM(-8, -4, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const bullet_sprite_metasprites[1] = {
	bullet_sprite_metasprite0
};
