//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bullet_lvl3_sprite_H
#define METASPRITE_bullet_lvl3_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bullet_lvl3_sprite_TILE_ORIGIN 0
#define bullet_lvl3_sprite_TILE_W 8
#define bullet_lvl3_sprite_TILE_H 16
#define bullet_lvl3_sprite_WIDTH 16
#define bullet_lvl3_sprite_HEIGHT 16
#define bullet_lvl3_sprite_TILE_COUNT 4
#define bullet_lvl3_sprite_PALETTE_COUNT 1
#define bullet_lvl3_sprite_COLORS_PER_PALETTE 4
#define bullet_lvl3_sprite_TOTAL_COLORS 4
#define bullet_lvl3_sprite_PIVOT_X 8
#define bullet_lvl3_sprite_PIVOT_Y 8
#define bullet_lvl3_sprite_PIVOT_W 16
#define bullet_lvl3_sprite_PIVOT_H 16
extern const metasprite_t* const bullet_lvl3_sprite_metasprites[1];

BANKREF_EXTERN(bullet_lvl3_sprite)

extern const palette_color_t bullet_lvl3_sprite_palettes[4];
extern const uint8_t bullet_lvl3_sprite_tiles[64];

#endif
