//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_early_gameboyfont_H
#define METASPRITE_early_gameboyfont_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define early_gameboyfont_TILE_ORIGIN 0
#define early_gameboyfont_TILE_W 8
#define early_gameboyfont_TILE_H 8
#define early_gameboyfont_WIDTH 336
#define early_gameboyfont_HEIGHT 8
#define early_gameboyfont_TILE_COUNT 41
#define early_gameboyfont_PALETTE_COUNT 1
#define early_gameboyfont_COLORS_PER_PALETTE 4
#define early_gameboyfont_TOTAL_COLORS 4

BANKREF_EXTERN(early_gameboyfont)

extern const palette_color_t early_gameboyfont_palettes[4];
extern const uint8_t early_gameboyfont_tiles[656];

#endif
