//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_ennemy16x16_sprite_H
#define METASPRITE_ennemy16x16_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ennemy16x16_sprite_TILE_ORIGIN 0
#define ennemy16x16_sprite_TILE_W 8
#define ennemy16x16_sprite_TILE_H 16
#define ennemy16x16_sprite_WIDTH 8
#define ennemy16x16_sprite_HEIGHT 16
#define ennemy16x16_sprite_TILE_COUNT 4
#define ennemy16x16_sprite_PALETTE_COUNT 1
#define ennemy16x16_sprite_COLORS_PER_PALETTE 4
#define ennemy16x16_sprite_TOTAL_COLORS 4
#define ennemy16x16_sprite_PIVOT_X 4
#define ennemy16x16_sprite_PIVOT_Y 8
#define ennemy16x16_sprite_PIVOT_W 8
#define ennemy16x16_sprite_PIVOT_H 16
extern const metasprite_t* const ennemy16x16_sprite_metasprites[2];

BANKREF_EXTERN(ennemy16x16_sprite)

extern const palette_color_t ennemy16x16_sprite_palettes[4];
extern const uint8_t ennemy16x16_sprite_tiles[64];

#endif
