//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_ennemylargebullet_sprite_H
#define METASPRITE_ennemylargebullet_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ennemylargebullet_sprite_TILE_ORIGIN 0
#define ennemylargebullet_sprite_TILE_W 8
#define ennemylargebullet_sprite_TILE_H 16
#define ennemylargebullet_sprite_WIDTH 16
#define ennemylargebullet_sprite_HEIGHT 16
#define ennemylargebullet_sprite_TILE_COUNT 4
#define ennemylargebullet_sprite_PALETTE_COUNT 1
#define ennemylargebullet_sprite_COLORS_PER_PALETTE 4
#define ennemylargebullet_sprite_TOTAL_COLORS 4
#define ennemylargebullet_sprite_PIVOT_X 8
#define ennemylargebullet_sprite_PIVOT_Y 8
#define ennemylargebullet_sprite_PIVOT_W 16
#define ennemylargebullet_sprite_PIVOT_H 16
extern const metasprite_t* const ennemylargebullet_sprite_metasprites[1];

BANKREF_EXTERN(ennemylargebullet_sprite)

extern const palette_color_t ennemylargebullet_sprite_palettes[4];
extern const uint8_t ennemylargebullet_sprite_tiles[64];

#endif
