//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_ennemy_2_sprite_H
#define METASPRITE_ennemy_2_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ennemy_2_sprite_TILE_ORIGIN 0
#define ennemy_2_sprite_TILE_W 8
#define ennemy_2_sprite_TILE_H 16
#define ennemy_2_sprite_WIDTH 16
#define ennemy_2_sprite_HEIGHT 16
#define ennemy_2_sprite_TILE_COUNT 4
#define ennemy_2_sprite_PALETTE_COUNT 1
#define ennemy_2_sprite_COLORS_PER_PALETTE 4
#define ennemy_2_sprite_TOTAL_COLORS 4
#define ennemy_2_sprite_PIVOT_X 8
#define ennemy_2_sprite_PIVOT_Y 8
#define ennemy_2_sprite_PIVOT_W 16
#define ennemy_2_sprite_PIVOT_H 16
extern const metasprite_t* const ennemy_2_sprite_metasprites[1];

BANKREF_EXTERN(ennemy_2_sprite)

extern const palette_color_t ennemy_2_sprite_palettes[4];
extern const uint8_t ennemy_2_sprite_tiles[64];

#endif
