//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_rock8x8_sprite_H
#define METASPRITE_rock8x8_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define rock8x8_sprite_TILE_ORIGIN 0
#define rock8x8_sprite_TILE_W 8
#define rock8x8_sprite_TILE_H 16
#define rock8x8_sprite_WIDTH 8
#define rock8x8_sprite_HEIGHT 16
#define rock8x8_sprite_TILE_COUNT 2
#define rock8x8_sprite_PALETTE_COUNT 1
#define rock8x8_sprite_COLORS_PER_PALETTE 4
#define rock8x8_sprite_TOTAL_COLORS 4
#define rock8x8_sprite_PIVOT_X 4
#define rock8x8_sprite_PIVOT_Y 8
#define rock8x8_sprite_PIVOT_W 8
#define rock8x8_sprite_PIVOT_H 16
extern const metasprite_t* const rock8x8_sprite_metasprites[1];

BANKREF_EXTERN(rock8x8_sprite)

extern const palette_color_t rock8x8_sprite_palettes[4];
extern const uint8_t rock8x8_sprite_tiles[32];

#endif
