//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_space_bkg_map_H
#define METASPRITE_space_bkg_map_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define space_bkg_map_TILE_ORIGIN 0
#define space_bkg_map_TILE_W 8
#define space_bkg_map_TILE_H 8
#define space_bkg_map_WIDTH 160
#define space_bkg_map_HEIGHT 256
#define space_bkg_map_TILE_COUNT 0
#define space_bkg_map_PALETTE_COUNT 1
#define space_bkg_map_COLORS_PER_PALETTE 4
#define space_bkg_map_TOTAL_COLORS 4
#define space_bkg_map_MAP_ATTRIBUTES 0
extern const unsigned char space_bkg_map_map[640];
#define space_bkg_map_map_attributes space_bkg_map_map

BANKREF_EXTERN(space_bkg_map)


#endif
