//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(ennemybullet_sprite)

const palette_color_t ennemybullet_sprite_palettes[4] = {
	RGB8(255,255,255), RGB8(169,169,169), RGB8( 84, 84, 84), RGB8(  0,  0,  0)
	
};

const uint8_t ennemybullet_sprite_tiles[16] = {
	0x00,0x00,0x18,0x3c,
	0x3c,0x66,0x66,0x5a,
	0x64,0x5a,0x3c,0x66,
	0x18,0x3c,0x00,0x00
	
};

const metasprite_t ennemybullet_sprite_metasprite0[] = {
	METASPR_ITEM(-4, -4, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const ennemybullet_sprite_metasprites[1] = {
	ennemybullet_sprite_metasprite0
};
