//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_ennemybullet_sprite_H
#define METASPRITE_ennemybullet_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ennemybullet_sprite_TILE_ORIGIN 0
#define ennemybullet_sprite_TILE_W 8
#define ennemybullet_sprite_TILE_H 8
#define ennemybullet_sprite_WIDTH 8
#define ennemybullet_sprite_HEIGHT 8
#define ennemybullet_sprite_TILE_COUNT 1
#define ennemybullet_sprite_PALETTE_COUNT 1
#define ennemybullet_sprite_COLORS_PER_PALETTE 4
#define ennemybullet_sprite_TOTAL_COLORS 4
#define ennemybullet_sprite_PIVOT_X 4
#define ennemybullet_sprite_PIVOT_Y 4
#define ennemybullet_sprite_PIVOT_W 8
#define ennemybullet_sprite_PIVOT_H 8
extern const metasprite_t* const ennemybullet_sprite_metasprites[1];

BANKREF_EXTERN(ennemybullet_sprite)

extern const palette_color_t ennemybullet_sprite_palettes[4];
extern const uint8_t ennemybullet_sprite_tiles[16];

#endif
