//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(powerup_sprite)

const palette_color_t powerup_sprite_palettes[4] = {
	RGB8(255,255,255), RGB8(169,169,169), RGB8( 84, 84, 84), RGB8(  0,  0,  0)
	
};

const uint8_t powerup_sprite_tiles[16] = {
	0xbd,0x7e,0x7e,0x81,
	0xff,0xb9,0xff,0xa5,
	0xff,0xb9,0xff,0xa1,
	0x7e,0x81,0xbd,0x7e
	
};

const metasprite_t powerup_sprite_metasprite0[] = {
	METASPR_ITEM(-4, -4, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const powerup_sprite_metasprites[1] = {
	powerup_sprite_metasprite0
};
