//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_rock8x8_H
#define METASPRITE_rock8x8_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define rock8x8_TILE_ORIGIN 0
#define rock8x8_TILE_W 8
#define rock8x8_TILE_H 8
#define rock8x8_WIDTH 8
#define rock8x8_HEIGHT 8
#define rock8x8_TILE_COUNT 1
#define rock8x8_PALETTE_COUNT 1
#define rock8x8_COLORS_PER_PALETTE 4
#define rock8x8_TOTAL_COLORS 4
#define rock8x8_PIVOT_X 4
#define rock8x8_PIVOT_Y 4
#define rock8x8_PIVOT_W 8
#define rock8x8_PIVOT_H 8
extern const metasprite_t* const rock8x8_metasprites[1];

BANKREF_EXTERN(rock8x8)

extern const palette_color_t rock8x8_palettes[4];
extern const uint8_t rock8x8_tiles[16];

#endif
