//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_splashscreen_H
#define METASPRITE_splashscreen_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define splashscreen_TILE_ORIGIN 0
#define splashscreen_TILE_W 8
#define splashscreen_TILE_H 8
#define splashscreen_WIDTH 160
#define splashscreen_HEIGHT 144
#define splashscreen_TILE_COUNT 100
#define splashscreen_PALETTE_COUNT 1
#define splashscreen_COLORS_PER_PALETTE 4
#define splashscreen_TOTAL_COLORS 4
#define splashscreen_MAP_ATTRIBUTES 0
extern const unsigned char splashscreen_map[360];
#define splashscreen_map_attributes splashscreen_map

BANKREF_EXTERN(splashscreen)

extern const palette_color_t splashscreen_palettes[4];
extern const uint8_t splashscreen_tiles[1600];

#endif
